trigger:
  - master

jobs:
  - job: android
    pool:
      vmImage: "macos-latest"
    variables:
      - group: secrets
      - group: general
      - name: androidReleaseDir
        value: $(build.artifactStagingDirectory)/build/app/outputs/flutter-apk
      - name: apkFile
        value: $(androidReleaseDir)/app-release.apk
    steps:
      - task: FlutterInstall@0
        displayName: "Install Flutter"
        inputs:
          
          channel: "stable"
          version: "custom"
          customVersion: "2.2.3"
      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: "."
          buildNumber: ""